import type { Metadata } from "next";
import { site } from "@/config/site";

const DEFAULT_TITLE = "Shoirly: signed proof of what your AI agent did";

// The social card generated by src/app/opengraph-image.tsx. Page-level openGraph
// replaces the file-based image, so it's attached explicitly to every page.
const ogImage = {
  url: `${site.url}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: "Shoirly: signed proof of what your AI agent did, and who approved it.",
};

type PageMetaInput = {
  /** Page title without the brand suffix. Omit for the home page. */
  title?: string;
  description: string;
  /** Path on the canonical host, starting with "/". */
  path: string;
  type?: "website" | "article";
  publishedTime?: string;
  noindex?: boolean;
};

/**
 * Builds page metadata so the canonical URL and og:url always match, on the
 * canonical host (https://shoirly.com). Page-level openGraph replaces the
 * layout's, so the shared fields are repeated here.
 */
export function pageMetadata({ title, description, path, type = "website", publishedTime, noindex }: PageMetaInput): Metadata {
  const url = path === "/" ? site.url : `${site.url}${path}`;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: url },
    openGraph: {
      type,
      url,
      siteName: site.name,
      locale: "en_IE",
      title: title ? `${title} | ${site.name}` : DEFAULT_TITLE,
      description,
      images: [ogImage],
      ...(publishedTime ? { publishedTime } : {}),
    },
    twitter: { card: "summary_large_image", images: [ogImage.url] },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}
